on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: k8stestcontainer.azurecr.io
        username: ${{ secrets.acr_k8stestcontainer_username }}
        password: ${{ secrets.acr_k8stestcontainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t k8stestcontainer.azurecr.io/akstest003:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push k8stestcontainer.azurecr.io/akstest003:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akstest003_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-test-003be2e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-test-003be2e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-test-003be2e
        container-registry-url: k8stestcontainer.azurecr.io
        container-registry-username: ${{ secrets.acr_k8stestcontainer_username }}
        container-registry-password: ${{ secrets.acr_k8stestcontainer_password }}
        secret-name: akstest003dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-test-003be2e
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          k8stestcontainer.azurecr.io/akstest003:${{ github.sha }}
        imagepullsecrets: |
          akstest003dockerauth
